services:
  server:
    container_name: memigo_server
    build: .
    ports:
      - "80:80"

    command: deno run -A --watch main.ts

    develop:
      watch:
        - path: deno.json
          action: rebuild
        - path: ./
          target: /app
          action: sync
